#!/bin/bash

ENV=${1:-staging}

if [ "$ENV" = "prod" ]; then
  NAME=nginx_prod
else
  NAME=nginx_staging
fi

podman stop $NAME 2>/dev/null
podman rm $NAME 2>/dev/null

echo "๐งน Container $NAME stopped & removed"

